apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
    kubevirt.ui/provider: fedora
    argocd.argoproj.io/sync-wave: "2"
  name: fedora
  namespace: virt-manage
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    volumeMode: Filesystem
  source:
    registry:
      url: docker://quay.io/gsosads/containerdisks/fedora:latest
      pullMethod: node
