apiVersion: v1  
kind: Namespace  
metadata:  
  name: app-dev  
  labels:  
    env: dev  
    app.example/line-of-business: demo  
---  
apiVersion: v1  
kind: Namespace  
metadata:  
  name: app-test  
  labels:  
    env: test  
    app.example/line-of-business: demo  
---  
apiVersion: v1  
kind: Namespace  
metadata:  
  name: app-prod  
  labels:  
    env: prod  
    app.example/line-of-business: demo  
